"""empty message

Revision ID: 0642a9779296
Revises: 2c708b4adc1c
Create Date: 2026-02-19 20:30:27.975281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0642a9779296'
down_revision = '2c708b4adc1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['id_user'], ['id'])

    with op.batch_alter_table('withdraws', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('bank_details',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('processed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdraws', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('bank_details',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('motors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###
