"""empty message

Revision ID: 124803f34d4a
Revises: 71219b897497
Create Date: 2026-02-18 13:02:37.685431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124803f34d4a'
down_revision = '71219b897497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motor_upgrades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('motor_id', sa.Integer(), nullable=False),
    sa.Column('valor_pago', sa.Float(), nullable=False),
    sa.Column('data_upgrade', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['motor_id'], ['motors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motor_upgrades')
    # ### end Alembic commands ###
