"""empty message

Revision ID: 71219b897497
Revises: 594d809277bf
Create Date: 2026-02-18 12:23:13.583077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71219b897497'
down_revision = '594d809277bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motors', schema=None) as batch_op:
        batch_op.drop_column('cycle_days')
        batch_op.drop_column('yield_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yield_rate', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('cycle_days', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
