"""empty message

Revision ID: 80ea81980dab
Revises: 86f6fdc6281f
Create Date: 2026-03-03 08:33:49.584165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ea81980dab'
down_revision = '86f6fdc6281f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdraws', schema=None) as batch_op:
        batch_op.alter_column('iban',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdraws', schema=None) as batch_op:
        batch_op.alter_column('iban',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
