"""empty message

Revision ID: 86f6fdc6281f
Revises: 88b8cc01d4eb
Create Date: 2026-02-26 11:11:03.774055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f6fdc6281f'
down_revision = '88b8cc01d4eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdraws', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iban', sa.String(length=50), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('bank_details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdraws', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_details', sa.TEXT(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('iban')

    # ### end Alembic commands ###
